services:
  web:
    build:
      context: .
      target: build
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - v-node-modules:/app/node_modules
    # Mantém o container vivo mesmo sem ter os scripts do Vite ainda
    command: npm run dev -- --host 0.0.0.0
    # command: tail -f /dev/null
    # command: sh -c "npm run dev -- --host 0.0.0.0"
    # restart: unless-stopped
    restart: "no"

volumes:
  v-node-modules: